services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT_DOCKER}
    depends_on:
      - cadvisor
      - alertmanager
      - grafana
    networks:
      - prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - ${CADVISOR_PORT}:${CADVISOR_PORT_DOCKER}
    networks:
      - prometheus
    restart: unless-stopped
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PORT}:${ALERTMANAGER_PORT_DOCKER}
    networks:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT_DOCKER}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - prometheus
#    env_file:
#      - ./grafana/config.monitoring
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - ${NODE_EXPORTER_PORT}:${NODE_EXPORTER_PORT_DOCKER}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
    networks:
      - prometheus
    restart: unless-stopped

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - ./config/blackbox-exporter/:/etc/blackbox_exporter/
      - blackbox_exporter_data:/blackbox_exporter
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    ports:
      - ${BLACKBOX_EXPORTER_PORT}:${BLACKBOX_EXPORTER_PORT_DOCKER}
    networks:
      - prometheus
    restart: unless-stopped   
  
volumes:
    prometheus_data: {}
    alertmanager_data: {}
    grafana_data: {}
    blackbox_exporter_data: {}

networks:
    prometheus:
