services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' 
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT_DOCKER}
    depends_on:
      - cadvisor
      - alertmanager
      - grafana
    networks:
      - prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:var/lib/docker:ro
    ports:
      - ${CADVISOR_PORT}:${CADVISOR_PORT_DOCKER}
    networks:
      - prometheus
    restart: unless-stopped
    deploy:
      mode: global
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PORT}:${ALERTMANAGER_PORT_DOCKER}
    networks:
      - prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT_DOCKER}
    networks:
      - prometheus
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped

  volumes:
      prometheus_data: {}
      alertmanager_data: {}
      grafana_data: {}

  networks:
      prometheus:
